### ISSUE TITLE
ValueError: Only scalar actions are supported now

### ISSUE THREAD

**Issue by syllebra** [DylanCope/Multi-Agent-RL-with-TF#1]
Hello Dylan.
Great tutorial! It seems to be a good basis for multiplayer card games using tf-agents.

I tried it outside the notebook and, with "last" version of tf-agents, I get this error after running the first tf implementation of the agent "player 1":

_Traceback (most recent call last):
  File "d:\DeepLearning\tf-agents-cards\multi-agents.py", line 277, in <module>
    name='Player1'
  File "d:\DeepLearning\tf-agents-cards\multi-agents.py", line 79, in __init__
    **dqn_kwargs)
  File "D:\DeepLearning\tf-agents-cards\env\lib\site-packages\gin\config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "D:\DeepLearning\tf-agents-cards\env\lib\site-packages\gin\utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "D:\DeepLearning\tf-agents-cards\env\lib\site-packages\gin\config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "D:\DeepLearning\tf-agents-cards\env\lib\site-packages\tf_agents\agents\dqn\dqn_agent.py", line 217, in __init__
    self._check_action_spec(action_spec)
  File "D:\DeepLearning\tf-agents-cards\env\lib\site-packages\tf_agents\agents\dqn\dqn_agent.py", line 297, in _check_action_spec
    .format(action_spec))
ValueError: Only scalar actions are supported now, but action spec is: BoundedTensorSpec(shape=(1,), dtype=tf.int32, name=None, minimum=array(0), maximum=array(8))
  In call to configurable 'DqnAgent' (<class 'tf_agents.agents.dqn.dqn_agent.DqnAgent'>)_

And here are my packages list:
_Package                  Version
------------------------ ---------
absl-py                  0.10.0
astunparse               1.6.3
backcall                 0.2.0
cachetools               4.1.1
certifi                  2020.6.20
chardet                  3.0.4
cloudpickle              1.3.0
colorama                 0.4.3
cycler                   0.10.0
decorator                4.4.2
dm-tree                  0.1.5
EasyProcess              0.3
gast                     0.3.3
gin-config               0.3.0
google-auth              1.21.1
google-auth-oauthlib     0.4.1
google-pasta             0.2.0
grpcio                   1.32.0
gym                      0.10.11
h5py                     2.10.0
idna                     2.10
imageio                  2.4.0
importlib-metadata       1.7.0
ipython                  7.18.1
ipython-genutils         0.2.0
jedi                     0.17.2
Keras-Preprocessing      1.1.2
kiwisolver               1.2.0
Markdown                 3.2.2
matplotlib               3.3.1
numpy                    1.18.5
oauthlib                 3.1.0
opencv-python            4.4.0.42
opt-einsum               3.3.0
pandas                   1.1.2
parso                    0.7.1
pickleshare              0.7.5
Pillow                   7.2.0
pip                      20.2.3
prompt-toolkit           3.0.7
protobuf                 3.13.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyglet                   1.5.7
Pygments                 2.6.1
pyparsing                2.4.7
python-dateutil          2.8.1
pytz                     2020.1
PyVirtualDisplay         1.3.2
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
scipy                    1.4.1
seaborn                  0.11.0
setuptools               50.3.0
six                      1.15.0
tensorboard              2.3.0
tensorboard-plugin-wit   1.7.0
tensorflow-gpu           2.3.0
tensorflow-gpu-estimator 2.3.0
tensorflow-probability   0.11.0
termcolor                1.1.0
tf-agents                0.6.0
traitlets                5.0.4
urllib3                  1.25.10
wcwidth                  0.2.5
Werkzeug                 1.0.1
wheel                    0.35.1
wrapt                    1.12.1
zipp                     3.1.0_

Do you have any idea about this error? May it be related to tf-agents version (0.6.0) or to the gpu tensorflow?
Thanks!

**Comment by syllebra** [comment]
Self answer. Replacing the tensor size in _action_spec_ seems to work with this version:

    def action_spec(self):
        position_spec = BoundedArraySpec((), np.int32, minimum=0, maximum=8)
        value_spec = BoundedArraySpec((), np.int32, minimum=1, maximum=2)
        return {
            'position': position_spec,
            'value': value_spec
        }

**Comment by DylanCope** [comment]
Thank you for pointing this out :) I will have a closer look at this later and make changes to the code
